Update README and CODEOWNERS
waterloo-rocketry/omnibus pull request #221
Opened 2024-05-19 04:49 UTC by Darth-Raazi

## Description

- Updated `README.md` to advertise `setup.sh` script
- Added Mohamed, Patrick and Elizabeth to `CODEOWNERS`

This PR closes #217 and #220.

2024-05-20 15:55 UTC, BigLiban requested changes
Everything looks good Ozayr, no issues at all. There's only one comment to look at, but that is it.

2024-05-20 15:55 UTC, BigLiban commented on .github/CODEOWNERS
> +* @waterloo-rocketry/default-reviewers @Darth-Raazi @BigLiban @patrick-gu @Lucifersan
Add Saad in here too as he would to like to also be requested for review on PRs too

2024-05-20 20:38 UTC, Darth-Raazi reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/221)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @BigLiban, @BluCodeGH, @jeffrey-huang-yz, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)

___
*[`.github/CODEOWNERS` line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/221#gh-1606956808:-NyMiWzW9wXqbc4JDXJE:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6f5f146b854afe0ab1500a9da4601189535f4d5f/.github/CODEOWNERS#L4)):*
<details><summary><i>Previously, BigLiban (Mohamed Bekdach) wrote…</i></summary><blockquote>

Add Saad in here too as he would to like to also be requested for review on PRs too
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-23 03:08 UTC, BigLiban approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/221)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH, @jeffrey-huang-yz, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)



<!-- Sent from Reviewable.io -->

2024-05-23 03:18 UTC, patrick-gu approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/221#-:-NyFnBL3EYPm_EWtLTxo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH, @jeffrey-huang-yz, @KavinSatheeskumar, @Lucifersan, and @saads312)



<!-- Sent from Reviewable.io -->

2024-05-24 02:19 UTC, merged