Image widget improvements
waterloo-rocketry/omnibus pull request #228
Opened 2024-06-06 00:28 UTC by patrick-gu

## Description
So far, I'm just rendering the image with `QPainter` so the resolution is preserved.

This PR closes #200.

## Developer Testing

Here's what I did to test my changes:

- Added the image widget with a PNG

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Check that the widget looks good on your machine

2024-06-11 06:10 UTC, Darth-Raazi approved these changes
Amazing work on this Patrick! One thing: can we have an "original size" option where it makes the image whatever the dimensions of the actual file are? Also I think this should be the default when an image is added (to avoid big borders), and the user can then resize if they want

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/228#-:-O-4tURx4ZkQ6WcjyOzG:bohm444)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)



<!-- Sent from Reviewable.io -->

2024-06-14 04:57 UTC, Darth-Raazi requested changes
Looks like you've got double overlapping labels?
![image.png](https://files.reviewableusercontent.io/images/reviewable/67076803/b4pTLvyD-Muaq1n91l2YPQ50/image.png)

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/228#-:-O-K5WG8CYyWBrl3uKvF:b-thoy1t)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)



<!-- Sent from Reviewable.io -->

2024-06-15 03:45 UTC, patrick-gu commented
That's really odd, since it's a builtin `ActionParameter`. No idea why that's happening

2024-06-15 03:54 UTC, patrick-gu commented
I think that only happens on dark mode. I would be inclined to think this is a problem with PyQtGraph because I'm not actually dealing with rendering the button

2024-06-15 21:31 UTC, patrick-gu commented
@Darth-Raazi This is an issue in PyQtGraph: https://github.com/pyqtgraph/pyqtgraph/issues/2380 and I've worked around it

2024-06-16 01:02 UTC, Darth-Raazi approved these changes
Wow talk about edge case bug lol. Your fix works so I think we're good to go

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/228#-:-O-TZAULEbadl55E3suG:b-pmdk2w)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)



<!-- Sent from Reviewable.io -->

2024-06-16 01:04 UTC, merged