Implement rlcs uart on dashboard
waterloo-rocketry/omnibus pull request #247
Opened 2024-07-05 20:28 UTC by Pdada1

## Description
Changed RLCS.py to include tank heating values on dashboard, adding battery, current, kelvin sensor 
Currently the files have an error where they cannot see the number definition in parsley. To temporarily fix this Number was hardcode defined

N/A

- Connected to RLCS Clientside and was able to see new states
- Tested alongside Tank Heating board, was able to read values off dashboard

2024-07-05 23:19 UTC, JasonBrave requested changes

2024-07-05 23:19 UTC, JasonBrave commented on sources/rlcs/rlcs.py
> +    Numeric("Heater Battery 1_Voltage", 16,scale=1/1000, big_endian=False),
Why there's a underscore before voltage

2024-07-05 23:40 UTC, KavinSatheeskumar approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/247#-:-O14GGRLBNHfYpVffGbS:bnfp4nl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @BigLiban, @BluCodeGH, @Darth-Raazi, @Lucifersan, @patrick-gu, @Pdada1, and @saads312)



<!-- Sent from Reviewable.io -->

2024-07-06 03:57 UTC, patrick-gu approved these changes
I trust that this is correct

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/247#-:-O15B38q3F4U4a-NGG6S:bzbkvl5)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @BluCodeGH, @Darth-Raazi, @JasonBrave, @Lucifersan, @Pdada1, and @saads312)



<!-- Sent from Reviewable.io -->

2024-07-06 04:00 UTC, merged