Fix Period CAN Sender
waterloo-rocketry/omnibus pull request #282
Opened 2024-08-07 04:03 UTC by Darth-Raazi

## Description

- Added actuator title to Periodic CAN Sender
- ON --> flash green, OFF --> flash red
- Fixed fake parsley having outdated message types

## Developer Testing

Here's what I did to test my changes:

- Ran Periodic CAN Sender with fake parsley and verified flashing, title, messages sent
- Ran dashboard with 2 plots, SDI, dynamic text and periodic CAN sender through WDR globallog data and nothing broke

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Run with fake parsley and verify intended behaviour
- Run connected to actual Parsley and verify intended behaviour (@BluCodeGH @patrick-gu can one of you do this?)

2024-08-08 02:43 UTC, patrick-gu requested changes
Unfortunately I don't know how to test this with actual parsley right now but I'll try to do that when I get a chance

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/282#-:-O3jrOoG9ihaNsKX7x3o:b-xjthr1)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @BluCodeGH, @Darth-Raazi, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/282#-O3jqY878lZllrq4u0EG:-O3jqY878lZllrq4u0EH:b7r1171) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/998cd499d41ddef6ce407cd7fed344d6ad46b02d/sinks/dashboard/items/periodic_can_sender.py#L26)):*
> ```Python
>         self.setLayout(self.layout)
> 
>         self.label = QLabel(self.actuator)
> ```

This doesn't update when you change the actuator


<!-- Sent from Reviewable.io -->

2024-08-10 00:24 UTC, Darth-Raazi reviewed
Thanks!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/282#-:-O3tevoTAZuBjt_NtabW:b-ucfknh)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @BigLiban, @BluCodeGH, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/282#-O3jqY878lZllrq4u0EG:-O3texhO62ElHdjv-reR:b-u6p238) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/998cd499d41ddef6ce407cd7fed344d6ad46b02d/sinks/dashboard/items/periodic_can_sender.py#L26)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

This doesn't update when you change the actuator
</blockquote></details>

Lol how did I miss that? Fixed


<!-- Sent from Reviewable.io -->

2024-08-10 01:03 UTC, patrick-gu approved these changes
Still not tested actually but LGTM, thanks!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/282#-:-O3tnpFGDycu20TRvrwf:bsv5nw1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @BluCodeGH, @Lucifersan, and @saads312)



<!-- Sent from Reviewable.io -->

2024-08-11 20:44 UTC, patrick-gu commented
Tested with injector board, it is sending messages correctly

2024-08-11 21:15 UTC, merged