Eridium V2 LCF1 Cold Flow Omnibus Config
waterloo-rocketry/omnibus pull request #297
Opened 2024-09-27 19:49 UTC by Pdada1

Eridium V2 LCF1 Cold Flow Omnibus Config for review for LCF2

2024-09-27 19:52 UTC, JasonBrave requested changes

2024-09-27 19:52 UTC, JasonBrave commented on sources/ni/config.py
> +    Sensor("FPT101 - Fill Injector", ports[12], 10, Connection.SINGLE,
```suggestion
    Sensor("FPT101 - Fuel Injector", ports[12], 10, Connection.SINGLE,

```

2024-11-02 22:28 UTC, zangjiucheng approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/297)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @patrick-gu, @Pdada1, and @saads312)



<!-- Sent from Reviewable.io -->

2025-02-25 04:18 UTC, closed without merging

2025-02-25 04:19 UTC, ChrisYx511 commented
Production configuration of Omnibus now happens exclusively on the DAQ box and not in the Git Repo. Only an example config file is provided.

2025-02-25 04:22 UTC, ChrisYx511 commented
See context: https://waterloorocketry.slack.com/archives/C01535M46SC/p1737847064000939