Remove plotter config
waterloo-rocketry/omnibus pull request #41
Opened 2021-12-06 05:12 UTC by BluCodeGH

I realized that if we make parsers own multiple series, one for each series they are parsing, it removes the need for a separate plotter config file.

Parsers are now singletons which are fed omnibus messages and return a list of series parsed from those messages.
Series are just responsible for acting like a ring buffer and computing the rolling average.
The plotter currently waits for one second worth of omnibus messages, during which parsers set up their series, and then plots that set of series. This should be changed soon by switching to a dynamic layout using pyqtgraph's dockable widgets.

2021-12-23 17:01 UTC, KavinSatheeskumar requested changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @addison-ch, @BluCodeGH, @chrissank, @DevinLeamy, @DhritiGabani, @eugeneh1217, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/parsers_test.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41#-MrbyduX8OMz6sfnJ5eB:-MrbyduX8OMz6sfnJ5eC:bowoclg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d0ac00388dcb17fd9b5c0d9dd46e58afb5fa88b5/sinks/plot/parsers_test.py#L60)):*
> ```Python
>         data = []
>         p = parsers.ParsleyParser("MSG_TYPE")
>         p.parse_can = data.append
> ```

I had to message you on slack in order to figure out what you were doing and why. Please add a comment describing your parsleyParser interface over-writing shenanigans.

Smh, why must python suck so much that you can mutate the interface of a class? Is safety a concept that is lost on today's youth? Has mutability finally gone so far that it is mutating the very foundation of society?


<!-- Sent from Reviewable.io -->

2021-12-23 23:01 UTC, BluCodeGH reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @addison-ch, @chrissank, @DevinLeamy, @DhritiGabani, @eugeneh1217, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/parsers_test.py, line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41#-MrbyduX8OMz6sfnJ5eB:-MrdWeb64qTUAenFmBUx:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d0ac00388dcb17fd9b5c0d9dd46e58afb5fa88b5/sinks/plot/parsers_test.py#L60)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

I had to message you on slack in order to figure out what you were doing and why. Please add a comment describing your parsleyParser interface over-writing shenanigans.

Smh, why must python suck so much that you can mutate the interface of a class? Is safety a concept that is lost on today's youth? Has mutability finally gone so far that it is mutating the very foundation of society?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-15 01:24 UTC, PCModeActivate requested changes
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41)* status: all files reviewed, 3 unresolved discussions (waiting on @addison-ch, @BluCodeGH, @chrissank, @DevinLeamy, @DhritiGabani, @eugeneh1217, @KavinSatheeskumar, and @wendi-yu)

___
*[sinks/plot/parsers_test.py, line 26 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41#-MtQIToF-iIMGBMtfz4k:-MtQIToF-iIMGBMtfz4l:b-25mqw5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f5317667efcf87bc144469d0f7aadb2980acc7b/sinks/plot/parsers_test.py#L26)):*
> ```Python
>         payload = {
>             "timestamp": 0,
>             "data": {"SENSOR 1": [1, 2, 6], "SENSOR 2": [4, 5, 6]}
> ```

Why 1,2,6?
___
*[sinks/plot/series.py, line 33 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41#-MtQJkZZ38wJswkNvD0Q:-MtQJkZZ38wJswkNvD0R:b-1cm30) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f5317667efcf87bc144469d0f7aadb2980acc7b/sinks/plot/series.py#L33)):*
> ```Python
>         """
> 
>         if time - self.last < 1 / config.GRAPH_RESOLUTION:
> ```

What is the unit of time here? Just wondering. It should be second?


<!-- Sent from Reviewable.io -->

2022-01-16 00:35 UTC, KavinSatheeskumar approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41#-:-MtVIcDS3y5XuiaGWj7A:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @addison-ch, @BluCodeGH, @chrissank, @DevinLeamy, @DhritiGabani, @eugeneh1217, @KavinSatheeskumar, and @wendi-yu)



<!-- Sent from Reviewable.io -->

2022-01-16 00:35 UTC, KavinSatheeskumar approved these changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41)* status: all files reviewed, 2 unresolved discussions (waiting on @addison-ch, @BluCodeGH, @chrissank, @DevinLeamy, @DhritiGabani, @eugeneh1217, and @wendi-yu)



<!-- Sent from Reviewable.io -->

2022-01-16 01:47 UTC, BluCodeGH reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @addison-ch, @chrissank, @DevinLeamy, @DhritiGabani, @eugeneh1217, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/parsers_test.py, line 26 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41#-MtQIToF-iIMGBMtfz4k:-MtVZ9gI-2GkwGf1KVn3:blm251m) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f5317667efcf87bc144469d0f7aadb2980acc7b/sinks/plot/parsers_test.py#L26)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Why 1,2,6?
</blockquote></details>

I wanted to make sure it wasn't just return the middle element. Clarified in a comment.
___
*[sinks/plot/series.py, line 33 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41#-MtQJkZZ38wJswkNvD0Q:-MtVZF60Exqjfe82WZ_g:bvj0lbv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f5317667efcf87bc144469d0f7aadb2980acc7b/sinks/plot/series.py#L33)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

What is the unit of time here? Just wondering. It should be second?
</blockquote></details>

Yep, seconds. Clarified.


<!-- Sent from Reviewable.io -->

2022-01-16 20:18 UTC, PCModeActivate approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @addison-ch, @chrissank, @DevinLeamy, @DhritiGabani, @eugeneh1217, and @wendi-yu)



<!-- Sent from Reviewable.io -->

2022-01-16 20:19 UTC, PCModeActivate approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/41#-:-MtZXm4C5DT5OwJxTARs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @addison-ch, @chrissank, @DevinLeamy, @DhritiGabani, @eugeneh1217, and @wendi-yu)



<!-- Sent from Reviewable.io -->

2022-01-16 20:19 UTC, merged