3d plot dash item
waterloo-rocketry/omnibus pull request #94
Opened 2023-02-11 15:37 UTC by KavinSatheeskumar

2023-02-11 20:46 UTC, BluCodeGH requested changes
Looks like this needs a rebase?

> Reviewed 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-:-NO1DZ1N5tnw58D4pEFF:b-mkzdht)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @Darth-Raazi, @KavinSatheeskumar, and @Panizghi)

___
*[`sinks/dashboard/savefile.sav` line 0 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NO1DK782WXM-prFB6sA:-NO1DK790cfsBfS2Vff4:b-n3t3ua) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1db920cba53880140c5424acd6df06d392dab7f/sinks/dashboard/savefile.sav#L0)):*
Please don't commit binary files.
___
*[`sinks/globallog/2023_01_21-05_19_31_PM.csv` line 0 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NO1DNJp-7TiBPtGFrHn:-NO1DNJp-7TiBPtGFrHo:bwzbejt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1db920cba53880140c5424acd6df06d392dab7f/sinks/globallog/2023_01_21-05_19_31_PM.csv#L0)):*
Or CSV files.
___
*[`sinks/globallog/2023_01_28-01_47_03_PM.csv` line 0 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NO1DOfqAKYrlA7O3x0h:-NO1DOfqAKYrlA7O3x0i:bf8vl11) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1db920cba53880140c5424acd6df06d392dab7f/sinks/globallog/2023_01_28-01_47_03_PM.csv#L0)):*
Really anything that you didn't mean to commit.


<!-- Sent from Reviewable.io -->

2023-02-12 19:44 UTC, Darth-Raazi reviewed
Can we add `.csv` to the gitignore? Also your savefile should be `.json`, not `.sav`, that change was made a while ago...

2023-02-14 21:47 UTC, BluCodeGH requested changes
> Reviewed 1 of 3 files at r1, 3 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: all files reviewed, 10 unresolved discussions (waiting on @KavinSatheeskumar and @Panizghi)

___
*[`sinks/dashboard/dashboard.py` line 3 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGbP4D9JLMeahisFoO:-NOGbP4D9JLMeahisFoP:b-6g7ez5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/dashboard.py#L3)):*
> ```Python
> import pickle
> import os
> import time
> ```

Unused `pickle` and `time` imports.
___
*[`sinks/dashboard/parsers.py` line 85 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGbW-W3fm0XHjCRx1R:-NOGbW-W3fm0XHjCRx1S:baheg22) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/parsers.py#L85)):*
> ```Python
>     # Note, we plan to revist the way that CAN message are handled
> 
> @Register("Payload")
> ```

Can we rename this to `StateEstimation` to avoid re-using the word `payload`?
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 17 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGr3NMAoarqa2IYM6o:-NOGr3NMAoarqa2IYM6p:b9ocw0j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L17)):*
> ```Python
> import time
> 
> #if there is error for opengl use the following command to install the acc : sudo easy_install pyopengl
> ```

This should be in a `requirements.txt`.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGcF57AlhrwGuy2hrP:-NOGcF57AlhrwGuy2hrQ:b-9nurct) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L49)):*
> ```Python
> 
>         # subscribe to stream dictated by properties
>         if self.props[1]:
> ```

Really feels like we should split this into two dash items, one for position and another for orientation, rather than having a bunch of if/else code smushed together.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 66 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsCG35NocoiWd-zzY:-NOGsCG35NocoiWd-zzZ:b-ciom25) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L66)):*
> ```Python
>         # add it to the layout
>         self.layout.addWidget(self.view, 0, 0)
>         self.start_time = time.time()
> ```

Unused.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 82 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsNgKBxPANWa9Fgg0:-NOGsNgKBxPANWa9Fgg1:b-4ev3xg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L82)):*
> ```Python
>         enable_orientation = True if orientation_mode == "Orientation" else False
> 
>         channel_and_series = prompt_user(
> ```

We should prompt for the data series before asking other questions.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 113 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsYiC8GKXxOW21q-c:-NOGsYiC8GKXxOW21q-d:b-6olylp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L113)):*
> ```Python
>         self.zaxis.setData(pos=zlist, color=(0.0,0.0,1.0,1.0))
> 
>     def transform(self, point, euler_angle):
> ```

`transform` and your `Rx`, `Ry`, `Rz` functions need comments explaining what they do.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 156 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsoZO29mBNEMEY43y:-NOGsoZO29mBNEMEY43z:b-xhs8w4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L156)):*
> ```Python
> 
> if __name__ == '__main__':    
>     pg.exec()
> ```

I don't think these last two lines should exist.
___
*[`sources/fakeload/main.py` line 1 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGtBHeBjpVeV4pqyUH:-NOGtBHeBjpVeV4pqyUI:bwqzmuw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sources/fakeload/main.py#L1)):*
> ```Python
> from omnibus import Sender
> ```

`fakeload` isn't a super clear name, prefer maybe `payload_fake`?
___
*[`sources/fakeload/main.py` line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGstjc3bPe98FaECqv:-NOGstjc3bPe98FaECqw:bx6dp0f) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sources/fakeload/main.py#L7)):*
> ```Python
> 
> READ_BULK = 200  # mimic how the real NI box samples in bulk for better performance
> SAMPLE_RATE = 10000  # total samples/second
> ```

READ_BULK is unused, you should just have SAMPLE_RATE and set it to something more reasonable like 10.


<!-- Sent from Reviewable.io -->

2023-02-21 00:22 UTC, KavinSatheeskumar reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: 4 of 10 files reviewed, 10 unresolved discussions (waiting on @BluCodeGH and @Panizghi)

___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGcF57AlhrwGuy2hrP:-NOl2q541LkgF1092mso:b169t5v) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L49)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Really feels like we should split this into two dash items, one for position and another for orientation, rather than having a bunch of if/else code smushed together.
</blockquote></details>

Me and @Panizghi were chatting and we kinda came to the conclusion that there is enough overlap that splitting into two dash items just kinda results in a lot of redundant code. This is the only if-else block in the program, the rest of the split is actually quite small in total, just which update you call really.


<!-- Sent from Reviewable.io -->

2023-02-21 20:38 UTC, BluCodeGH requested changes
@Panizghi When you make changes please open reviewable and reply to the respective comments (just something like "Done") to help everyone keep track of what's been addressed and what hasn't been. For example it looks like you've missed addressing some of my comments.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-:-NOpgDRP7W2ni8i8mxF-:b-kfglsn)* status: 4 of 10 files reviewed, 10 unresolved discussions (waiting on @KavinSatheeskumar and @Panizghi)

___
*[`sinks/dashboard/parsers.py` line 85 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGbW-W3fm0XHjCRx1R:-NOpg58u-nvjxFn7PVaO:b-wr9pz3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/parsers.py#L85)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Can we rename this to `StateEstimation` to avoid re-using the word `payload`?
</blockquote></details>

Note that I meant everything (function names, class names, file names, etc) should be renamed, not just this one line.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGcF57AlhrwGuy2hrP:-NOpfgtH-Qo4wLytzmef:bp6p0jb) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L49)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Me and @Panizghi were chatting and we kinda came to the conclusion that there is enough overlap that splitting into two dash items just kinda results in a lot of redundant code. This is the only if-else block in the program, the rest of the split is actually quite small in total, just which update you call really.
</blockquote></details>

On the contrary, the only code that's re-used between the two "modes" is the 20 lines above this comment. Otherwise, the code is entirely separate. It's much better to duplicate 20 lines than have the other 130 lines mixed together unnecessarily.


<!-- Sent from Reviewable.io -->

2023-02-21 21:15 UTC, Panizghi reviewed
My apologies I will make sure to do so 

> Reviewed 1 of 3 files at r4, 1 of 4 files at r5, 3 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-:-NOpp3TmC9EvEZZpkDw2:br2c58q)* status: 8 of 10 files reviewed, 10 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)



<!-- Sent from Reviewable.io -->

2023-02-21 21:17 UTC, Panizghi reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: 8 of 10 files reviewed, 10 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 17 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGr3NMAoarqa2IYM6o:-NOppJo4BfALMf6RKCMl:b-7tfmjp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L17)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This should be in a `requirements.txt`.
</blockquote></details>

added
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 156 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsoZO29mBNEMEY43y:-NOppR891u-lRsfa0zQq:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L156)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I don't think these last two lines should exist.
</blockquote></details>

done
___
*[`sources/fakeload/main.py` line 1 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGtBHeBjpVeV4pqyUH:-NOppTemAdzDPz1sNeeg:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sources/fakeload/main.py#L1)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`fakeload` isn't a super clear name, prefer maybe `payload_fake`?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-03-05 21:18 UTC, KavinSatheeskumar reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: 7 of 11 files reviewed, 13 unresolved discussions (waiting on @BluCodeGH and @Panizghi)

___
*[`sinks/dashboard/items/payload_plot_position.py` line 67 at r9](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPncS1T3WYTVp022W58:-NPncS1T3WYTVp022W59:bcibkzq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/087f914bb2bab397ef8b5c450ac6272c7181c133/sinks/dashboard/items/payload_plot_position.py#L67)):*
> ```Python
>         )
> 
>         enable_orientation = False
> ```

Same comments as above
___
*[`sinks/dashboard/items/payload_plot_position.py` line 79 at r9](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPncTNQ3QN6shJYix_2:-NPncTNQ3QN6shJYix_3:b-t9eajk) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/087f914bb2bab397ef8b5c450ac6272c7181c133/sinks/dashboard/items/payload_plot_position.py#L79)):*
> ```Python
>             return None
> 
>         return [channel_and_series, enable_orientation]
> ```

Just pointing out that you should not add "enable_orientation" to the props
___
*[`sinks/dashboard/items/payload_plot_orientation.py` line 75 at r9](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPnbx2pA-ZEzenBiis5:-NPnbx2q7VNXJy0rckOt:bsr3a39) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/087f914bb2bab397ef8b5c450ac6272c7181c133/sinks/dashboard/items/payload_plot_orientation.py#L75)):*
> ```Python
>         )
> 
>         enable_orientation = True 
> ```

Now that we have split the dash_item into two, this prompt is not needed.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGcF57AlhrwGuy2hrP:-NPnc7-a8OprXX0S9wo4:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L49)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

On the contrary, the only code that's re-used between the two "modes" is the 20 lines above this comment. Otherwise, the code is entirely separate. It's much better to duplicate 20 lines than have the other 130 lines mixed together unnecessarily.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-05 21:54 UTC, Panizghi reviewed
> Reviewed 4 of 4 files at r3, 1 of 5 files at r7, 1 of 3 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: all files reviewed, 12 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/payload_plot_position.py` line 67 at r9](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPncS1T3WYTVp022W58:-NPnjvsW7BRhTBxUXjE4:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/087f914bb2bab397ef8b5c450ac6272c7181c133/sinks/dashboard/items/payload_plot_position.py#L67)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Same comments as above
</blockquote></details>

done
___
*[`sinks/dashboard/items/payload_plot_position.py` line 79 at r9](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPncTNQ3QN6shJYix_2:-NPnji1L8BITnxnpW7bl:b-7ql1td) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/087f914bb2bab397ef8b5c450ac6272c7181c133/sinks/dashboard/items/payload_plot_position.py#L79)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Just pointing out that you should not add "enable_orientation" to the props
</blockquote></details>

fixed
___
*[`sinks/dashboard/items/payload_plot_orientation.py` line 75 at r9](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPnbx2pA-ZEzenBiis5:-NPnjm107ebCDmPUCV_L:b-7ql1td) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/087f914bb2bab397ef8b5c450ac6272c7181c133/sinks/dashboard/items/payload_plot_orientation.py#L75)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Now that we have split the dash_item into two, this prompt is not needed.
</blockquote></details>

fixed
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 66 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsCG35NocoiWd-zzY:-NPnjnTF3t31R24n8j4o:b-7ql1td) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L66)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

fixed
___
*[`sources/fakeload/main.py` line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGstjc3bPe98FaECqv:-NPnjWuB3kkpxIMfc8kC:b-6gfzuy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sources/fakeload/main.py#L7)):*
> StateEstimation
SAMPLE_RATE is updated to 10 
new variable WAIT_TIME used for sleep time


<!-- Sent from Reviewable.io -->

2023-03-05 22:32 UTC, KavinSatheeskumar reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: 6 of 11 files reviewed, 12 unresolved discussions (waiting on @BluCodeGH and @Panizghi)

___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 82 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsNgKBxPANWa9Fgg0:-NPntk_UDre7ITvfZrTL:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L82)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

We should prompt for the data series before asking other questions.
</blockquote></details>

Done.
___
*[`sources/fakeload/main.py` line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGstjc3bPe98FaECqv:-NPnttcJD8nLp6UgVYWy:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sources/fakeload/main.py#L7)):*
<details><summary><i>Previously, Panizghi (Paniz Ojaghi) wrote…</i></summary><blockquote>

> StateEstimation
SAMPLE_RATE is updated to 10 
new variable WAIT_TIME used for sleep time
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-05 23:46 UTC, BluCodeGH requested changes
Looking good, just some tweaks to be made. Remember that none of your function / file / class names should mention "Payload" since everything we're doing here is either generic (3d position / orientation views) or state estimation-specific (parsers).

> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-:-NPo9ZWS98OHs34Y-f3Q:b-4953od)* status: all files reviewed, 9 unresolved discussions (waiting on @KavinSatheeskumar and @Panizghi)

___
*[`sinks/dashboard/dashboard.py` line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPo8K3bBLB1TdfAU_e3:-NPo8K3cDMqFx0qlT3B1:b-iosgx3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e2b3640642c66edf0ee7b9479b29f0f6706ee166/sinks/dashboard/dashboard.py#L14)):*
> ```Python
> from items.plot_dash_item import PlotDashItem
> from items.payloads_plot_dash_item import PayloadDashItem 
> from items.can_message_table import CanMsgTableDashItem
> ```

Remember to always test your code. Removing these imports means these dashitems never get added to the registry and so can't ever be added to the dashboard.
___
*[`sinks/dashboard/parsers.py` line 87 at r10](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPo9A816ghGaB0o3F6q:-NPo9A816ghGaB0o3F6r:bk72kxu) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/65aa7a0a04c4f32e8b1eabc3fa7596cfd0476f0c/sinks/dashboard/parsers.py#L87)):*
> ```Python
> 
> @Register("StateEstimation")
> def payload_parser(state_est):
> ```

The argument to this function should still be `payload`, since it refers to the payload of the omnibus message. However, the function itself is the state estimation parser, not the payload parser, and should be named as such.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 66 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsCG35NocoiWd-zzY:-NPo6JF1-hU0CJQGH0dm:b-31i0qc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L66)):*
<details><summary><i>Previously, Panizghi (Paniz Ojaghi) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

`self.start_time` is still unused?
___
*[`sources/fakeload/main.py` line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGstjc3bPe98FaECqv:-NPo6qnqABNHY8hVPidD:b-eolybe) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sources/fakeload/main.py#L7)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Well now `SAMPLE_RATE` is unused. You should remove `WAIT_TIME` and sleep for `1 / SAMPLE_RATE` seconds.
___
*[`sources/payload_fake/main.py` line 55 at r10](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPo74-RBW1VMnzCOv5U:-NPo74-SD4Ek6acu8-vH:bhszf88) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/65aa7a0a04c4f32e8b1eabc3fa7596cfd0476f0c/sources/payload_fake/main.py#L55)):*
> ```Python
> 
>     sender.send(CHANNEL, data)
>     time.sleep(max(WAIT_TIME - (time.time() - start), 0))
> ```

This `max` logic isn't necessary anymore, we can just `time.sleep(1 / SAMPLE_RATE)`.


<!-- Sent from Reviewable.io -->

2023-03-10 17:19 UTC, Panizghi reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 66 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsCG35NocoiWd-zzY:-NQBWKdA4SMr706W1oID:b-hfpv0l) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L66)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`self.start_time` is still unused?
</blockquote></details>

removed
___
*[`sources/fakeload/main.py` line 7 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGstjc3bPe98FaECqv:-NQBWCQeESP3u_DwBAg0:bt2vr0x) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sources/fakeload/main.py#L7)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Well now `SAMPLE_RATE` is unused. You should remove `WAIT_TIME` and sleep for `1 / SAMPLE_RATE` seconds.
</blockquote></details>

Fixed 
___
*[`sources/payload_fake/main.py` line 55 at r10](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NPo74-RBW1VMnzCOv5U:-NQBWEQNDjLRX2ur5Hl4:b-qssebz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/65aa7a0a04c4f32e8b1eabc3fa7596cfd0476f0c/sources/payload_fake/main.py#L55)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This `max` logic isn't necessary anymore, we can just `time.sleep(1 / SAMPLE_RATE)`.
</blockquote></details>

fixed 


<!-- Sent from Reviewable.io -->

2023-03-10 17:21 UTC, Panizghi approved these changes
> Reviewed 2 of 2 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: all files reviewed, 9 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)



<!-- Sent from Reviewable.io -->

2023-03-10 17:22 UTC, Panizghi approved these changes
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: all files reviewed, 9 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)



<!-- Sent from Reviewable.io -->

2023-03-15 18:35 UTC, BluCodeGH requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: all files reviewed, 6 unresolved discussions (waiting on @KavinSatheeskumar)

___
*[`sinks/dashboard/items/payload_plot_position.py` line 21 at r12](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NQaY4aF6OS2EfGpqnOW:-NQaY4aF6OS2EfGpqnOX:b-iaeb98) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/0dbeedd024978cfd317cefa57035a61bf29a9405/sinks/dashboard/items/payload_plot_position.py#L21)):*
> ```Python
> 
> @Register
> class PayloadDashItem (DashboardItem):
> ```

Same file and class name comment.
___
*[`sinks/dashboard/items/payload_plot_orientation.py` line 17 at r12](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NQaXal7BuXxN-tbK3Yt:-NQaXal8AASU5RBbpkti:b-7zh9on) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/0dbeedd024978cfd317cefa57035a61bf29a9405/sinks/dashboard/items/payload_plot_orientation.py#L17)):*
> ```Python
> import time
> 
> # if there is error for opengl use the following command to install the acc : sudo easy_install pyopengl
> ```

Given we've put opengl in `requirements.txt` this comment isn't necessary. Also it's prone to confusing people since it's unix-specific and "acc" isn't a word lol.
___
*[`sinks/dashboard/items/payload_plot_orientation.py` line 22 at r12](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NQaXSjt9NPkicL0Y4Q3:-NQaXSjt9NPkicL0Y4Q4:b-h5cbp2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/0dbeedd024978cfd317cefa57035a61bf29a9405/sinks/dashboard/items/payload_plot_orientation.py#L22)):*
> ```Python
> 
> @Register
> class PayloadDashItem (DashboardItem):
> ```

This file has nothing to do with payload, it is a generic 3d orientation plot. The file name and class name should reflect that.
___
*[`sinks/dashboard/items/payloads_plot_dash_item.py` line 113 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NOGsYiC8GKXxOW21q-c:-NQaYNjJ3KLW5xT9w_cM:buf7tys) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8f55b552bad31c77348996267e9503e478722704/sinks/dashboard/items/payloads_plot_dash_item.py#L113)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`transform` and your `Rx`, `Ry`, `Rz` functions need comments explaining what they do.
</blockquote></details>

Bump on this.


<!-- Sent from Reviewable.io -->

2023-03-17 04:03 UTC, BluCodeGH requested changes
Sorry for the last few nitpicks, I promise I'll approve once these are taken care of. Remember, your plots are just generic position and orientation plotters, they aren't state-estimation specific either. Please rename the files to `plot_3d_orientation.py` and `plot_3d_position.py`.

> Reviewed 2 of 9 files at r13, 1 of 5 files at r14, 1 of 7 files at r15, 1 of 6 files at r16, 1 of 6 files at r19, 4 of 6 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-:-NQhilFJ6Q3RmaxFd_mr:b-lpty07)* status: all files reviewed, 6 unresolved discussions (waiting on @KavinSatheeskumar)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 134 at r20](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NQhhYjUCappgZSWRw__:-NQhhYjUCappgZSWRw_a:b-5ne211) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/539e327183624c3f10dbe75e47559c6b0fba91c3/sinks/dashboard/items/plot_dash_item.py#L134)):*
> ```Python
>     def on_data_update(self, stream, payload):
>         time, point = payload
>         # desc = payload[2] if (len(payload) > 2) else ""
> ```

Delete this line? Seems like desc is never used.
___
*[`sinks/dashboard/items/state_estimation_plot_orientation.py` line 15 at r20](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NQhhgFrCd2q80AU4pWV:-NQhhgFrCd2q80AU4pWW:bn5r2xv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/539e327183624c3f10dbe75e47559c6b0fba91c3/sinks/dashboard/items/state_estimation_plot_orientation.py#L15)):*
> ```Python
> import config
> from utils import prompt_user
> import time
> ```

Unused imports pg, ConsoleWidget, LabelItem, TextItem np, config, time.
___
*[`sinks/dashboard/items/state_estimation_plot_orientation.py` line 21 at r20](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NQhiRug6PzGOH7GJZ4A:-NQhiRug6PzGOH7GJZ4B:b-ihjuqj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/539e327183624c3f10dbe75e47559c6b0fba91c3/sinks/dashboard/items/state_estimation_plot_orientation.py#L21)):*
> ```Python
> 
> @Register
> class OrientationDashItem (DashboardItem):
> ```

`Orientation3DDashItem` for consistency with the 3D in the position one.
___
*[`sinks/dashboard/items/state_estimation_plot_position.py` line 15 at r20](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NQhiYuQAMM2KgVon2li:-NQhiYuQAMM2KgVon2lj:b-joe1l7) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/539e327183624c3f10dbe75e47559c6b0fba91c3/sinks/dashboard/items/state_estimation_plot_position.py#L15)):*
> ```Python
> import config
> from utils import prompt_user
> import time
> ```

Same unused imports.


<!-- Sent from Reviewable.io -->

2023-03-21 04:12 UTC, itslinotlie reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94)* status: 9 of 13 files reviewed, 8 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/plot_3D_orientation.py` line 2 at r21](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NR1KIT39OB_AkLJiqXP:-NR1KIT39OB_AkLJiqXQ:b-3nhbcj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6c4365ef2093af90207b3cf303735cda6f1e0025/sinks/dashboard/items/plot_3D_orientation.py#L2)):*
> ```Python
> from publisher import publisher
> from pyqtgraph.Qt import QtWidgets
> ```

unused QtWidgets import (applies to both 3d files)
___
*[`sinks/dashboard/items/plot_3D_orientation.py` line 18 at r21](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-NR1LDQq7K_uS38J4Zo9:-NR1LDQq7K_uS38J4ZoA:b-36zrjk) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6c4365ef2093af90207b3cf303735cda6f1e0025/sinks/dashboard/items/plot_3D_orientation.py#L18)):*
> ```Python
> 
>         # Specify the layout
>         self.layout = QGridLayout()
> ```

GridLayout seems overkill seeing how you only add one item to the layout. Any of the QVBoxLayout  or QHBoxLayout would do the same and make it slightly easier to read? (I was personally expecting multiple widgets when I saw the grid layout)


<!-- Sent from Reviewable.io -->

2023-03-27 19:15 UTC, BluCodeGH approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, although autopep8 isn't happy atm.

> Reviewed 1 of 4 files at r21, 3 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-:-NRZUl7m2EhsXtTupnyQ:b7ea4de)* status: all files reviewed, 3 unresolved discussions (waiting on @KavinSatheeskumar)



<!-- Sent from Reviewable.io -->

2023-03-28 01:54 UTC, itslinotlie approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r3, 2 of 9 files at r13, 1 of 5 files at r14, 1 of 7 files at r15, 1 of 6 files at r19, 1 of 6 files at r20, 1 of 4 files at r21, 3 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-:-NR_tciS24WSZrl5WPVo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KavinSatheeskumar)



<!-- Sent from Reviewable.io -->

2023-04-04 00:17 UTC, Panizghi commented
autopep8 should be good, @KavinSatheeskumar fixed the GLError

2023-04-04 00:19 UTC, Panizghi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 9 files at r13, 1 of 5 files at r14, 1 of 7 files at r15, 1 of 6 files at r19, 1 of 6 files at r20, 1 of 4 files at r21, 2 of 3 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/94#-:-NS8cTSmECsEWCaWq0-n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KavinSatheeskumar)



<!-- Sent from Reviewable.io -->

2023-04-11 19:31 UTC, merged